name: skuf-services

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "studs"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: wiremock
    ports:
      - "8081:8081"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
    environment:
      - WIREMOCK_OPTIONS=--verbose
    command: ["--port", "8081", "--global-response-templating"]
