name: skuf-services

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: "studs"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"